### PR TITLE
Added Uzbek language

### PR DESCRIPTION
**Pull request by bahriddin**

### CODE REVIEW

**Comment by aldatsa** [comment]
Thank you very much for your translation! We will release a new version of our plugin soon. We will let you know

**Comment by aldatsa** [comment]
We have just released the version 1.3.5 of our plugin that includes your translation.

If you set CKEditor's language to Uzbek, you will notice that some of the strings of the plugin are in English (check the attached image). The reason is that we use some common translations that CKEditor provide, for example, alignment, left, right..., and those strings are not translated to Uzbek yet. CKEditor's own strings are translated by the community on Transifex: https://www.transifex.com/ckeditor/ckeditor/dashboard/
ckeditor-html5audio-uzbek

**Comment by bahriddin** [comment]
You're welcome. I will try to translate other words in transifex also. Thank you for quick response. Appreciate it :+1:

**Comment by bahriddin** [comment]
Hi @aldatsa 
I loved this little software and it meets all my needs. However, I can't find any normal video plugin like this. So I modified your plugin. I want to share with others if you don't mind, of course.

Here I am attaching my files:
[https://dl.dropboxusercontent.com/u/58147413/html5video.zip](url)

**Comment by aldatsa** [comment]
Hi @bahriddin,

That's really nice!

We released our plugin using a free software/open source copyleft license (GNU GPLv3). You have the right to modify and share it. No problem at all. It would be an honour for us. The only condition is releasing your derivative product as free software/open source using the same license.

I've just tested your plugin and works really well!

Could you make a little correction to the Basque translation? It's Bideo with B, not Video. Thanks!

Best regards

**Comment by bahriddin** [comment]
I corrected 'Bideo' and created repository in Github. You can see: https://github.com/bahriddin/ckeditor-html5-video

Thank you a lot!

**Pull request merged**
