### PR TITLE
Add Russian translation & tiny update in en.js

### PR DESCRIPTION
**Pull request by smartcorestudio**

### CODE REVIEW

**Comment by aldatsa** [comment]
Nice! We will include your translation in the next release. Thank you very much!

**Comment by aldatsa** [comment]
We have just released a new version (1.0.1) that includes the Russian translation and your fixes.

**Comment by aldatsa** [comment]
Hi @smartcorestudio, I don't want to bother you but we are going to release a new version soon. The main improvement is a new item in the context menu. I added a new string ('Audio properties') for this menu item. Would be nice if you could help us translate it to Russian. Is 'аудио свойства' correct?

**Comment by smartcorestudio** [comment]
Hi @aldatsa! Yes, it's correct, it's just little better to say "Свойства аудио". I've created a pull request. Feel free to ask me if you'll need any help. I will always be glad to help you if I can. Thanks for your work on improvement of this plugin!

**Pull request merged**
